language: java

notifications:
  slack:
    secure: h/9gumJqP6lF11J+T6+lCjz8LPNr9y5ta0EwppJfxOoDRRXfOWlhyOK2YO16Z8dAYy74VY2b6QHU2PPlPBMs3TsQ2ugNrvIZkY019IadXZLxmABN7I3IeolAvE67NfMGCWzgdAl/4b64tzhytxPw/VE53Haq3/Yy97Gc1fo/oQ3vtTBgAKsaSXWnNxmdzpDHuKElD86NZQVV3Usrz7AF/D6V9Po+QU/P3sXd+y2P9ZoYBlMpSpurUmo8e+pbZuqGqCookn/Pdt3EJtdyHVjdjBclOQK2dy7jVvmyckZxYNaOcDtTGXT32sVJ0NbhF0dKz6IQ0yb8VS8gbAPv1W2YXNfAfl0tM8HW8V9rm9UZm/GJIHzmSaZJa7zaLVKhnPCQllC3WVjXLt8UDpunoIR8n5GgJHw1fWHDiDMTdhyRo8uedReIa9dMBGzPmKsjSRBKxFWpHdcO+A9Rvb7fsPuFIRH1PoBYDvVMcCNeZymBUWU3S9Uso4wm6us0GLrBT3Aopf2qzHe1Xxu383iHu3pxyS64cv7QK7AkppiN0sl1S6omB7k/g8pmuxBdRBYAgOLYZP1yMixD92lSGrcslAODitq+jV/nhd0SViIVBIu2LCZ1q+dqCZbvwBEAXgN9n6qjcSZ0bzCHqcb6HIcpayCPcqmoYuxMOiT/NKW7EHX2Ong=

cache:
  directories:
    - $HOME/.m2

jdk:
  - openjdk7
  - oraclejdk7
  - oraclejdk8

env:
  global:
    - secure: cRtYZ1Zt0krQcwdHNkRD6z9F/N35ViSNhNmEecWPaeqRF64JFP+LyuNDuhk9hgHTGIEcUmgRpA+8sfrTHV8SM6TnDxQ41PS38MH0/atGSuGzvG6AoQLvR4RDOWq6RUErHRjSBeJeaBv6DOAkOXt2sRVQcE6tnovo8vRjSleJs3J160CO2Jr1Q1k/naVie/b1W2QaD+KEaGCGuNL1S5VMRRPNbj42MiCmargDAXKosoa2RgxLh2+j1kMf4dGht1QVd1AqjKknyd+mHd3XEKEV2svIlO8aJksg1MCbcxV5PXR26fYHd0naai3IS3pp2hn26GiQYNxfQDxDtoK97KbYAjb8ZUkI+tSEhWEZR8agvo8ACEZsXlzt/xVR5Ozheyvsf8KFcuvSXl6XWhoU/7EirqHFPjy9KEmXvW5AsxWqhtvOWL3jahzOi8L7idU9TwQn2oW8QlMYfBMLQM44zQBedc061Oyt0eqnDY/dWpqPLyb2jsj9j0VS939XX+Wsp1iXRFNk3jAXInlZUMcTyj0YDkykOXCPksBPlE6h/bJQQpAU40Ojj6gRyndFGwfe3lwMS10rehe6CDCO8T5WjZyNM15mz/wa9zX9WfJULx4QgNfl0h3VuP5f1WdzV4apeP9Gr/hk3iXFXEv0tkE/LrqVl7QbwxpJ3NnSVuEyzhaLxPA=
    - secure: UwjQdW3fzWB0Yoih4e2/oSZVcUyx3G4dAdUGpsBAznucq1HNdoAbmt6uUAD8TAYtxdiYMZZ/yHbolSHX8QpS7ayyOuyPO7tcEHdOzLUppGj90lD6lRNnJgqnHS+F1vVLqArWqrdO3Iva3hU9c65HdOJufc/HiWB2WTymdY5/yqQ/zkpCQ8RnGw6VhtzkZfa0uZtWFxERun4mmDcjExttg8gV3Spw3NcnYQ5DFxezDvjjMEFO5PV2n/ijk9xvR0wf5764VtAQC92vBWwCx1bGBoiBfT0pK9Zkk9mEmxDjvy4bwY8bSzUKCyrGoc680SWZFfYw/7ZLkETU8iMxcmXh7BsGW5fHBE/Gq/IEuU04oGq/fa8JjG7oKbBI97wkCMMNnvZbYfa5UYps0UtXaFcdGJdtx3xgN+z/LFh+Hs/WabvfyvgzTFXaxNxeedVr3VkOesNCKj3GQ/x+F93hohAKWDNwBPFIggPO3j4tJbXKF5jwgEal6ddevP3GHJJ8Bf0pcNE/DU+BQGo4VhWrRMqHUVmlAI4VJNmM0MWhf7kdhFhXbzg2taayDlw9/7okUIxr+YX3h5FSHxujjBi/Ay3k1/tVCxC2uESmm7E5vN/64cssM3f1fLxjbEEmSOE0lyMxWMp4LcSgEWq088FvZJmfv3L2aAlmZczyDF6xpmhlo7g=

before_install:
  - curl -sL https://github.com/jpm4j/jpm4j.installers/raw/master/dist/biz.aQute.jpm.run.jar >jpm4j.jar
  - java -jar jpm4j.jar -u init
  - ~/jpm/bin/jpm install com.codacy:codacy-coverage-reporter:assembly

after_success:
  - mvn jacoco:report coveralls:report
  - ~/jpm/bin/codacy-coverage-reporter -l Java -r target/site/jacoco/jacoco.xml
